export const governancePlanes = [
  {
    id: "projection",
    floor: 6,
    label: "Projection",
    qualifier: "Mirror",
    summary: "Freshness-bearing reflection of all five floors below.",
    color: "#66bfff",
  },
  {
    id: "intent",
    floor: 5,
    label: "Intent",
    qualifier: "Outcome",
    summary: "Requested outcome, boundaries, and final disposition.",
    color: "#65d6a4",
  },
  {
    id: "enduring-context",
    floor: 4,
    label: "Enduring Context",
    qualifier: "Meaning",
    summary: "Durable vocabulary, routing, rationale, and constraints.",
    color: "#6fc8dc",
  },
  {
    id: "grounding",
    floor: 3,
    label: "Grounding",
    qualifier: "Evidence",
    summary: "Verified placement, receipts, findings, and proof.",
    color: "#b69aeb",
  },
  {
    id: "canon",
    floor: 2,
    label: "Canon",
    qualifier: "Authority",
    summary: "Governing rules and the issued Job Order badge.",
    color: "#f1c86b",
  },
  {
    id: "actuality",
    floor: 1,
    label: "Actuality",
    qualifier: "Work",
    summary: "Terminal bounded work plane; simulated here, never executed.",
    color: "#ff786f",
  },
];

export const halls = [
  {
    id: "gatehouse",
    label: "Gatehouse",
    color: "gold",
    role: "Enforces structure and signals a candidate tripped Crossing.",
  },
  {
    id: "forge",
    label: "Forge",
    color: "orange",
    role: "Builds, evaluates, packages, and publishes reusable product source.",
  },
  {
    id: "assay",
    label: "Assay",
    color: "violet",
    role: "Performs read-only project and artifact judgment.",
  },
  {
    id: "ward",
    label: "Ward",
    color: "green",
    role: "Reports integration, transport, and health after checked evidence.",
  },
];

const steps = [
  {
    id: "mirror-route",
    planeId: "projection",
    direction: "down",
    title: "Read the mirror to route",
    location: "Projection mirror",
    worker: "Pawn",
    earnedAccess: [],
    gateResult: "not-entered",
    evidence: ["source", "freshness"],
    description: "Expose source, freshness, open lane, and Factory home without authorizing work.",
  },
  {
    id: "capture-intent",
    planeId: "intent",
    direction: "down",
    title: "Capture the audit outcome",
    location: "Foundry entrance",
    worker: "Pawn",
    earnedAccess: ["route:known"],
    gateResult: "clear",
    evidence: ["outcome", "privacy-boundary"],
    description: "Create a public-safe Job Order candidate for the Workbench Feedback audit.",
  },
  {
    id: "attach-context",
    planeId: "enduring-context",
    direction: "down",
    title: "Attach durable meaning",
    location: "Main Foundry Workspace",
    worker: "Pawn",
    earnedAccess: ["route:known", "context:bounded"],
    gateResult: "clear",
    evidence: ["vocabulary", "hall-boundary", "simulation-boundary"],
    description: "Bind the workflow vocabulary, Hall responsibilities, and confidentiality boundary.",
  },
  {
    id: "ground-candidate",
    planeId: "grounding",
    direction: "down",
    title: "Verify that the work belongs",
    location: "Gatehouse Crossing",
    worker: "Pawn",
    earnedAccess: ["route:known", "context:bounded", "placement:verified"],
    gateResult: "clear",
    evidence: ["placement-receipt", "collision-check", "proof-route"],
    description: "Verify the target, lane, scope, and evidence route before Canon issue.",
  },
  {
    id: "issue-order",
    planeId: "canon",
    direction: "down",
    title: "Issue the Canon-backed badge",
    location: "Gatehouse issue desk",
    worker: "Pawn",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "issued",
    evidence: ["job-order", "scope-badge", "required-proof"],
    description: "Issue one bounded audit order only after route, context, and placement pass.",
  },
  {
    id: "perform-audit",
    planeId: "actuality",
    direction: "down",
    title: "Perform the bounded Feedback audit",
    location: "Assay workbench",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["audit-observations", "named-findings"],
    description: "Inspect only the granted public product model; this simulator performs no real read or write.",
  },
  {
    id: "ground-results",
    planeId: "grounding",
    direction: "up",
    title: "Put down findings and proof",
    location: "Assay evidence bench",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["audit-verdict", "finding-receipts", "scope-check"],
    description: "Freeze the observed result and check it against the same Job Order.",
  },
  {
    id: "canon-disposition",
    planeId: "canon",
    direction: "up",
    title: "Check the governing disposition",
    location: "Gatehouse return Crossing",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["canon-conformance", "follow-on-boundary"],
    description: "Compare the result with the issued order without widening its scope.",
  },
  {
    id: "retain-lesson",
    planeId: "enduring-context",
    direction: "up",
    title: "Retain the durable lesson",
    location: "Main Foundry Workspace",
    worker: "Pawn",
    earnedAccess: ["record:context", "record:projection"],
    gateResult: "clear",
    evidence: ["retention-decision"],
    description: "Keep only durable vocabulary or rationale; do not copy live task state.",
  },
  {
    id: "dispose-intent",
    planeId: "intent",
    direction: "up",
    title: "Dispose the completed intent",
    location: "Foundry exit",
    worker: "Pawn",
    earnedAccess: ["record:projection"],
    gateResult: "clear",
    evidence: ["outcome-disposition", "next-intent"],
    description: "Close the completed order and make unresolved work explicit rather than hidden.",
  },
  {
    id: "refresh-mirror",
    planeId: "projection",
    direction: "up",
    title: "Refresh the Projection mirror",
    location: "Projection mirror",
    worker: "Pawn",
    earnedAccess: ["record:projection"],
    gateResult: "complete",
    evidence: ["status", "freshness", "trace-receipt"],
    description: "Render the completed run, receipts, and freshness without creating new authority.",
  },
];

export const feedbackAuditScenario = Object.freeze({
  schemaVersion: 1,
  id: "feedback-audit",
  shortId: "FEEDBACK-AUDIT",
  title: "Workbench Feedback Audit",
  summary: "A complete public-safe audit journey from Projection to Actuality and back.",
  boundary: "Simulation only · no Actuality changes",
  steps: Object.freeze(steps.map((step) => Object.freeze(step))),
});

export const scenarios = Object.freeze([feedbackAuditScenario]);

export function getPlane(planeId) {
  return governancePlanes.find((plane) => plane.id === planeId);
}
