export const governancePlanes = [
  {
    id: "projection",
    floor: 6,
    label: "Projection",
    qualifier: "Mirror",
    summary: "Freshness-bearing reflection of all five floors below.",
    color: "#66bfff",
  },
  {
    id: "intent",
    floor: 5,
    label: "Intent",
    qualifier: "Outcome",
    summary: "Requested outcome, boundaries, and final disposition.",
    color: "#65d6a4",
  },
  {
    id: "enduring-context",
    floor: 4,
    label: "Enduring Context",
    qualifier: "Meaning",
    summary: "Durable vocabulary, routing, rationale, and constraints.",
    color: "#6fc8dc",
  },
  {
    id: "grounding",
    floor: 3,
    label: "Grounding",
    qualifier: "Evidence",
    summary: "Verified placement, receipts, findings, and proof.",
    color: "#b69aeb",
  },
  {
    id: "canon",
    floor: 2,
    label: "Canon",
    qualifier: "Authority",
    summary: "Governing rules and the issued Job Order badge.",
    color: "#f1c86b",
  },
  {
    id: "actuality",
    floor: 1,
    label: "Actuality",
    qualifier: "Work",
    summary: "Terminal bounded work plane; simulated here, never executed.",
    color: "#ff786f",
  },
];

export const halls = [
  {
    id: "gatehouse",
    label: "Gatehouse",
    color: "gold",
    role: "Enforces structure and signals a candidate tripped Crossing.",
  },
  {
    id: "forge",
    label: "Forge",
    color: "orange",
    role: "Builds, evaluates, packages, and publishes reusable product source.",
  },
  {
    id: "assay",
    label: "Assay",
    color: "violet",
    role: "Performs read-only project and artifact judgment.",
  },
  {
    id: "ward",
    label: "Ward",
    color: "green",
    role: "Reports integration, transport, and health after checked evidence.",
  },
];

const steps = [
  {
    id: "mirror-route",
    structuralClasses: ["halls", "modules", "sockets"],
    specId: "SIM-SPEC-01",
    taskId: "SIM-TK-01",
    planeId: "projection",
    direction: "down",
    title: "Read the mirror to route",
    location: "Projection mirror",
    worker: "Pawn",
    earnedAccess: [],
    gateResult: "not-entered",
    evidence: ["source", "freshness"],
    description: "Expose source, freshness, open lane, and Factory home without authorizing work.",
  },
  {
    id: "capture-intent",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-01",
    taskId: "SIM-TK-02",
    planeId: "intent",
    direction: "down",
    title: "Capture the audit outcome",
    location: "Foundry entrance",
    worker: "Pawn",
    earnedAccess: ["route:known"],
    gateResult: "clear",
    evidence: ["outcome", "privacy-boundary"],
    description: "Create a public-safe Job Order candidate for the Workbench Feedback audit.",
  },
  {
    id: "attach-context",
    structuralClasses: ["halls", "modules", "sockets"],
    specId: "SIM-SPEC-02",
    taskId: "SIM-TK-03",
    planeId: "enduring-context",
    direction: "down",
    title: "Attach durable meaning",
    location: "Main Foundry Workspace",
    worker: "Pawn",
    earnedAccess: ["route:known", "context:bounded"],
    gateResult: "clear",
    evidence: ["vocabulary", "hall-boundary", "simulation-boundary"],
    description: "Bind the workflow vocabulary, Hall responsibilities, and confidentiality boundary.",
  },
  {
    id: "ground-candidate",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-02",
    taskId: "SIM-TK-04",
    planeId: "grounding",
    direction: "down",
    title: "Verify that the work belongs",
    location: "Gatehouse Crossing",
    worker: "Pawn",
    earnedAccess: ["route:known", "context:bounded", "placement:verified"],
    gateResult: "clear",
    evidence: ["placement-receipt", "collision-check", "proof-route"],
    description: "Verify the target, lane, scope, and evidence route before Canon issue.",
  },
  {
    id: "issue-order",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-03",
    taskId: "SIM-TK-05",
    planeId: "canon",
    direction: "down",
    title: "Issue the Canon-backed badge",
    location: "Gatehouse issue desk",
    worker: "Pawn",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "issued",
    evidence: ["job-order", "scope-badge", "required-proof"],
    description: "Issue one bounded audit order only after route, context, and placement pass.",
  },
  {
    id: "enter-actuality",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-03",
    taskId: "SIM-TK-05A",
    planeId: "actuality",
    direction: "down",
    title: "Enter the Actuality floor",
    location: "Foundry entrance",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["gatehouse-entry", "passageway-route"],
    description: "Enter through Gatehouse before moving across the Actuality floor to the assigned Hall.",
  },
  {
    id: "stage-actuality-workspace",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-03",
    taskId: "SIM-TK-05B",
    planeId: "actuality",
    direction: "down",
    title: "Stage work in the Foundry Workspace",
    location: "Main Foundry Workspace",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["passageway-progress", "workspace-staging"],
    description: "Move the Job Order through the central Workspace before entering its assigned Hall.",
  },
  {
    id: "perform-audit",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-03",
    taskId: "SIM-TK-06",
    planeId: "actuality",
    direction: "down",
    title: "Perform the bounded Feedback audit",
    location: "Assay workbench",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["audit-observations", "named-findings"],
    description: "Inspect only the granted public product model; this simulator performs no real read or write.",
  },
  {
    id: "ground-results",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-04",
    taskId: "SIM-TK-07",
    planeId: "grounding",
    direction: "up",
    title: "Put down findings and proof",
    location: "Assay evidence bench",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["audit-verdict", "finding-receipts", "scope-check"],
    description: "Freeze the observed result and check it against the same Job Order.",
  },
  {
    id: "canon-disposition",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-04",
    taskId: "SIM-TK-08",
    planeId: "canon",
    direction: "up",
    title: "Check the governing disposition",
    location: "Gatehouse return Crossing",
    worker: "Agent",
    earnedAccess: ["canon:read", "actuality:audit"],
    gateResult: "clear",
    evidence: ["canon-conformance", "follow-on-boundary"],
    description: "Compare the result with the issued order without widening its scope.",
  },
  {
    id: "retain-lesson",
    structuralClasses: ["halls", "modules", "sockets"],
    specId: "SIM-SPEC-05",
    taskId: "SIM-TK-09",
    planeId: "enduring-context",
    direction: "up",
    title: "Retain the durable lesson",
    location: "Main Foundry Workspace",
    worker: "Pawn",
    earnedAccess: ["record:context", "record:projection"],
    gateResult: "clear",
    evidence: ["retention-decision"],
    description: "Keep only durable vocabulary or rationale; do not copy live task state.",
  },
  {
    id: "dispose-intent",
    structuralClasses: ["halls"],
    specId: "SIM-SPEC-05",
    taskId: "SIM-TK-10",
    planeId: "intent",
    direction: "up",
    title: "Dispose the completed intent",
    location: "Foundry exit",
    worker: "Pawn",
    earnedAccess: ["record:projection"],
    gateResult: "clear",
    evidence: ["outcome-disposition", "next-intent"],
    description: "Close the completed order and make unresolved work explicit rather than hidden.",
  },
  {
    id: "refresh-mirror",
    structuralClasses: ["halls", "modules", "sockets"],
    specId: "SIM-SPEC-05",
    taskId: "SIM-TK-11",
    planeId: "projection",
    direction: "up",
    title: "Refresh the Projection mirror",
    location: "Projection mirror",
    worker: "Pawn",
    earnedAccess: ["record:projection"],
    gateResult: "complete",
    evidence: ["status", "freshness", "trace-receipt"],
    description: "Render the completed run, receipts, and freshness without creating new authority.",
  },
];

const jobOrderSpecs = [
  {
    id: "SIM-SPEC-01",
    title: "Route and capture the outcome",
    tasks: [
      { id: "SIM-TK-01", stepId: "mirror-route", title: "Read the mirror to route" },
      { id: "SIM-TK-02", stepId: "capture-intent", title: "Capture the audit outcome" },
    ],
  },
  {
    id: "SIM-SPEC-02",
    title: "Bind context and ground placement",
    tasks: [
      { id: "SIM-TK-03", stepId: "attach-context", title: "Attach durable meaning" },
      { id: "SIM-TK-04", stepId: "ground-candidate", title: "Verify that the work belongs" },
    ],
  },
  {
    id: "SIM-SPEC-03",
    title: "Authorize and perform bounded work",
    tasks: [
      { id: "SIM-TK-05", stepId: "issue-order", title: "Issue the Canon-backed badge" },
      { id: "SIM-TK-05A", stepId: "enter-actuality", title: "Enter the Actuality floor" },
      { id: "SIM-TK-05B", stepId: "stage-actuality-workspace", title: "Stage work in the Foundry Workspace" },
      { id: "SIM-TK-06", stepId: "perform-audit", title: "Perform the bounded Feedback audit" },
    ],
  },
  {
    id: "SIM-SPEC-04",
    title: "Ground and judge the result",
    tasks: [
      { id: "SIM-TK-07", stepId: "ground-results", title: "Put down findings and proof" },
      { id: "SIM-TK-08", stepId: "canon-disposition", title: "Check the governing disposition" },
    ],
  },
  {
    id: "SIM-SPEC-05",
    title: "Retain, dispose, and refresh",
    tasks: [
      { id: "SIM-TK-09", stepId: "retain-lesson", title: "Retain the durable lesson" },
      { id: "SIM-TK-10", stepId: "dispose-intent", title: "Dispose the completed intent" },
      { id: "SIM-TK-11", stepId: "refresh-mirror", title: "Refresh the Projection mirror" },
    ],
  },
];

export const feedbackAuditScenario = Object.freeze({
  schemaVersion: 1,
  id: "feedback-audit",
  shortId: "FEEDBACK-AUDIT",
  title: "Review a Harness",
  summary: "A complete public-safe audit journey from Projection to Actuality and back.",
  boundary: "Simulation only · no Actuality changes",
  jobOrder: Object.freeze({
    id: "FEEDBACK-AUDIT-JO-01",
    title: "Example Workbench Feedback Audit Job Order",
    specs: Object.freeze(jobOrderSpecs.map((spec) => Object.freeze({
      ...spec,
      tasks: Object.freeze(spec.tasks.map((task) => Object.freeze(task))),
    }))),
  }),
  steps: Object.freeze(steps.map((step) => Object.freeze({
    ...step,
    structuralClasses: step.structuralClasses ? Object.freeze([...step.structuralClasses]) : undefined,
    earnedAccess: Object.freeze([...step.earnedAccess]),
    evidence: Object.freeze([...step.evidence]),
  }))),
});

function createPremadeScenario({
  id,
  shortId,
  title,
  summary,
  jobOrderId,
  boundary = "Simulation only · no Actuality changes",
  terminalResult,
  steps: sourceSteps,
}) {
  const steps = sourceSteps.map((step, index) => {
    const specNumber = Math.floor(index / 2) + 1;
    return {
      structuralClasses: ["halls"],
      earnedAccess: [],
      evidence: [],
      ...step,
      id: `${id}-${step.id}`,
      specId: `${shortId}-SPEC-${String(specNumber).padStart(2, "0")}`,
      taskId: `${shortId}-TK-${String(index + 1).padStart(2, "0")}`,
    };
  });
  const specs = [];
  for (let index = 0; index < steps.length; index += 2) {
    const group = steps.slice(index, index + 2);
    specs.push({
      id: group[0].specId,
      title: `Governed stage ${Math.floor(index / 2) + 1}`,
      tasks: group.map((step) => ({ id: step.taskId, stepId: step.id, title: step.title })),
    });
  }
  return Object.freeze({
    schemaVersion: 1,
    id,
    shortId,
    title,
    summary,
    boundary,
    ...(terminalResult === undefined ? {} : { terminalResult }),
    jobOrder: Object.freeze({
      id: jobOrderId,
      title: `${title} Job Order`,
      specs: Object.freeze(specs.map((spec) => Object.freeze({
        ...spec,
        tasks: Object.freeze(spec.tasks.map((task) => Object.freeze(task))),
      }))),
    }),
    steps: Object.freeze(steps.map((step) => Object.freeze({
      ...step,
      structuralClasses: Object.freeze([...step.structuralClasses]),
      earnedAccess: Object.freeze([...step.earnedAccess]),
      evidence: Object.freeze([...step.evidence]),
    }))),
  });
}

export const jobOrderFlightScenario = createPremadeScenario({
  id: "job-order-flight",
  shortId: "JOB-ORDER-FLIGHT",
  title: "Fly a Job Order",
  summary: "One continuous order passes every S-037 lifecycle gate from freshness-visible routing through terminal plane accounting.",
  boundary: "Simulation only · modeled future workflow, not live or implemented automation",
  terminalResult: "closed-complete",
  jobOrderId: "JOB-ORDER-FLIGHT-JO-01",
  steps: [
    {
      id: "sitrep",
      planeId: "projection",
      direction: "down",
      title: "Sitrep",
      location: "Projection mirror",
      worker: "Pawn",
      gateResult: "not-entered",
      structuralClasses: ["halls", "modules", "sockets"],
      evidence: ["source", "freshness", "sitrep-to-preflight-handoff"],
      description: "Observe and route only. A named Canon-backed Job Order may proceed to Preflight; Sitrep never authorizes work.",
    },
    {
      id: "preflight",
      planeId: "grounding",
      direction: "down",
      title: "Preflight",
      location: "Validation and Gatehouse review",
      worker: "Pawn",
      gateResult: "clear",
      earnedAccess: ["canon:read", "actuality:read"],
      evidence: ["canon-issuance", "preflight-fingerprint", "landing-contract", "preflight-to-launch-handoff"],
      description: "Reconcile authority and live reality, then prove the lane can launch, recover, land, and close before emitting a freshness-bound handoff.",
    },
    {
      id: "launch-flight",
      planeId: "canon",
      direction: "down",
      title: "Launch-flight",
      location: "Gatehouse launch threshold",
      worker: "Pawn",
      gateResult: "issued",
      earnedAccess: ["canon:read", "claim:write", "lane:open"],
      evidence: ["steward-claim", "run-started-receipt", "launch-to-in-flight-handoff"],
      description: "The Steward serializes one claimant and writer lane, binds the landing contract, and records passage; the handoff opens no scope beyond the issued order.",
    },
    {
      id: "in-flight",
      planeId: "actuality",
      direction: "down",
      title: "In-flight",
      location: "Assigned producer lane",
      worker: "Agent",
      gateResult: "clear",
      earnedAccess: ["canon:read", "actuality:bounded-write"],
      evidence: ["red-green-proof", "remote-candidate", "in-flight-to-landing-check-handoff"],
      description: "Execute only the claimed slice, checkpoint recoverably, and hand off an immutable candidate. New scope returns to Canon and Preflight.",
    },
    {
      id: "landing-check",
      planeId: "grounding",
      direction: "up",
      title: "Landing-check",
      location: "Assay fixed-revision bench",
      worker: "Agent",
      gateResult: "clear",
      earnedAccess: ["candidate:read", "audit:write"],
      evidence: ["candidate-sha", "independent-verdict", "landing-check-to-land-handoff"],
      description: "An independent read-only checker accepts the exact remote candidate or returns it to In-flight; every changed candidate invalidates the verdict.",
    },
    {
      id: "land",
      planeId: "actuality",
      direction: "down",
      title: "Land",
      location: "Ward integration lane",
      worker: "Agent",
      gateResult: "clear",
      structuralClasses: ["halls", "sockets"],
      earnedAccess: ["integration:write"],
      evidence: ["landing-check-verdict", "integration-receipt", "land-to-postflight-check-handoff"],
      description: "Deliver the accepted payload by an explicit non-force transition. A moved target creates a new candidate and returns through Landing-check; landing is not closure.",
    },
    {
      id: "postflight-check",
      planeId: "projection",
      direction: "up",
      title: "PostFlight-check",
      location: "Projection mirror",
      worker: "Pawn",
      gateResult: "complete",
      structuralClasses: ["halls", "modules", "sockets"],
      earnedAccess: ["record:context", "record:projection"],
      evidence: ["plane-dispositions", "claim-release-receipt", "projection-freshness", "postflight-check-receipt"],
      description: "Start from verified Actuality and prove every other Governance Plane represents it. If Integration lacks its required PR or merge, hand the bounded repair to a fresh chat, wait, and recheck; otherwise preserve delivered-unclosed or recovery-required truth.",
    },
  ],
});

export const createAndAssignScenario = createPremadeScenario({
  id: "create-and-assign",
  shortId: "CREATE-ASSIGN",
  title: "Create & Assign a Job Order",
  summary: "Intake creates a candidate; Orchestration specifies, routes, and assigns it through checked passage.",
  jobOrderId: "CREATE-ASSIGN-JO-01",
  steps: [
    { id: "read-request", planeId: "projection", direction: "down", title: "Read the requested outcome", location: "Projection mirror", worker: "Pawn", gateResult: "not-entered", structuralClasses: ["halls", "modules", "sockets"], evidence: ["source", "freshness"], description: "Expose the public request and source freshness without launching work." },
    { id: "capture-candidate", planeId: "intent", direction: "down", title: "Create the candidate Job Order", location: "Intake candidate desk", worker: "Pawn", gateResult: "clear", earnedAccess: ["candidate:create"], evidence: ["requested-outcome", "candidate-receipt"], description: "Intake creates only a deterministic candidate and hands it onward." },
    { id: "validate-candidate", planeId: "grounding", direction: "down", title: "Validate scope and identity", location: "Validation review point", worker: "Pawn", gateResult: "clear", earnedAccess: ["candidate:read"], evidence: ["validation-finding", "identity-check"], description: "Validation emits a read-only finding for Orchestration." },
    { id: "specify-order", planeId: "canon", direction: "down", title: "Specify and issue the Job Order", location: "Orchestration planning desk", worker: "Pawn", gateResult: "issued", earnedAccess: ["canon:read", "assignment:write"], evidence: ["spec", "task", "scope-badge"], description: "Orchestration defines the task, route, owner, and required proof." },
    { id: "record-passage", planeId: "grounding", direction: "up", title: "Record protected passage", location: "Gatehouse passage", worker: "Pawn", gateResult: "clear", earnedAccess: ["assignment:read"], evidence: ["passage-receipt"], description: "Gatehouse scans declared inputs and records the passage without choosing the route." },
    { id: "assign-producer", planeId: "actuality", direction: "down", title: "Assign the bounded producer", location: "Assigned producer lane", worker: "Agent", gateResult: "clear", earnedAccess: ["assignment:write"], evidence: ["assignment-acknowledgement"], description: "The named producer accepts only the issued bounded Job Order." },
    { id: "refresh-projection", planeId: "projection", direction: "up", title: "Project the active assignment", location: "Projection mirror", worker: "Pawn", gateResult: "complete", structuralClasses: ["halls", "modules", "sockets"], earnedAccess: ["projection:write"], evidence: ["status", "freshness", "trace-receipt"], description: "Reflect the assignment and receipts without creating authority." },
  ],
});

export const producerUpdateScenario = createPremadeScenario({
  id: "producer-update",
  shortId: "PRODUCER-UPDATE",
  title: "Update a Product from its Producer",
  summary: "A producer change is built, checked, integrated, and projected through the declared product route.",
  jobOrderId: "PRODUCER-UPDATE-JO-01",
  steps: [
    { id: "detect-update", planeId: "projection", direction: "down", title: "Detect a producer change", location: "Projection mirror", worker: "Pawn", gateResult: "not-entered", structuralClasses: ["halls", "modules", "sockets"], evidence: ["producer-source", "freshness"], description: "Observe the declared producer change and its public recovery ref." },
    { id: "capture-outcome", planeId: "intent", direction: "down", title: "Capture the product update outcome", location: "Foundry entrance", worker: "Pawn", gateResult: "clear", earnedAccess: ["route:known"], evidence: ["target-product", "desired-version"], description: "State the bounded product result without assuming a release." },
    { id: "ground-source", planeId: "grounding", direction: "down", title: "Verify producer and target", location: "Validation review point", worker: "Pawn", gateResult: "clear", earnedAccess: ["producer:read"], evidence: ["source-proof", "target-proof", "collision-check"], description: "Verify the producer relationship, lane, and proof route." },
    { id: "issue-build", planeId: "canon", direction: "down", title: "Issue the bounded build order", location: "Orchestration planning desk", worker: "Pawn", gateResult: "issued", earnedAccess: ["canon:read", "forge:write"], evidence: ["job-order", "build-scope", "required-checks"], description: "Authorize only the declared producer build and product handoff." },
    { id: "build-producer", planeId: "actuality", direction: "down", title: "Build the producer change", location: "Forge producer bench", worker: "Agent", gateResult: "clear", structuralClasses: ["halls", "modules"], earnedAccess: ["forge:write"], evidence: ["build-artifact", "test-result"], description: "Forge builds and evaluates the reusable producer source." },
    { id: "review-artifact", planeId: "grounding", direction: "up", title: "Review the built artifact", location: "Assay review bench", worker: "Agent", gateResult: "clear", earnedAccess: ["artifact:read"], evidence: ["assay-verdict", "named-findings"], description: "Assay judges the artifact read-only against the Job Order." },
    { id: "integrate-product", planeId: "actuality", direction: "down", title: "Integrate the product update", location: "Ward integration lane", worker: "Agent", gateResult: "clear", structuralClasses: ["halls", "sockets"], earnedAccess: ["integration:write"], evidence: ["integration-receipt", "bounded-repair-count"], description: "Ward integrates the accepted artifact with at most one bounded repair." },
    { id: "refresh-product", planeId: "projection", direction: "up", title: "Project the updated product", location: "Projection mirror", worker: "Pawn", gateResult: "complete", structuralClasses: ["halls", "modules", "sockets"], earnedAccess: ["projection:write"], evidence: ["product-status", "freshness", "trace-receipt"], description: "Reflect the integrated product state; main promotion remains owner-only." },
  ],
});

export const releaseRecoveryScenario = createPremadeScenario({
  id: "release-recovery",
  shortId: "RELEASE-RECOVERY",
  title: "Recover a Release",
  summary: "A failed integration is frozen, diagnosed, repaired once, independently checked, and truthfully projected.",
  jobOrderId: "RELEASE-RECOVERY-JO-01",
  steps: [
    { id: "observe-failure", planeId: "projection", direction: "down", title: "Observe the failed release", location: "Projection mirror", worker: "Pawn", gateResult: "not-entered", structuralClasses: ["halls", "modules", "sockets"], evidence: ["failure-status", "freshness"], description: "Expose the failure and source without inferring its cause." },
    { id: "freeze-outcome", planeId: "intent", direction: "down", title: "Define the recovery outcome", location: "Foundry entrance", worker: "Pawn", gateResult: "clear", evidence: ["recovery-outcome", "stop-condition"], description: "Bound the desired recovery and the conditions that require owner review." },
    { id: "diagnose-failure", planeId: "grounding", direction: "down", title: "Diagnose from frozen evidence", location: "Assay review bench", worker: "Agent", gateResult: "clear", earnedAccess: ["failure:read"], evidence: ["root-cause", "reproduction"], description: "Assay reads the frozen evidence and names the failing assumption." },
    { id: "issue-repair", planeId: "canon", direction: "down", title: "Issue one bounded repair", location: "Orchestration planning desk", worker: "Pawn", gateResult: "issued", earnedAccess: ["canon:read", "repair:write"], evidence: ["repair-scope", "acceptance"], description: "Authorize one minimal repair without widening the release scope." },
    { id: "repair-release", planeId: "actuality", direction: "down", title: "Apply the bounded repair", location: "Ward repair lane", worker: "Agent", gateResult: "clear", structuralClasses: ["halls", "sockets"], earnedAccess: ["repair:write"], evidence: ["repair-receipt"], description: "Ward applies at most one repair through the declared integration route." },
    { id: "verify-recovery", planeId: "grounding", direction: "up", title: "Verify the recovered release", location: "Assay review bench", worker: "Agent", gateResult: "clear", earnedAccess: ["artifact:read"], evidence: ["independent-verdict", "regression-check"], description: "Assay independently judges the repaired result against the same order." },
    { id: "record-disposition", planeId: "canon", direction: "up", title: "Record the release disposition", location: "Orchestration return desk", worker: "Pawn", gateResult: "clear", earnedAccess: ["canon:read"], evidence: ["disposition", "owner-gate"], description: "Record whether integration may continue; main promotion stays owner-only." },
    { id: "refresh-recovery", planeId: "projection", direction: "up", title: "Project the recovery result", location: "Projection mirror", worker: "Pawn", gateResult: "complete", structuralClasses: ["halls", "modules", "sockets"], earnedAccess: ["projection:write"], evidence: ["release-status", "freshness", "trace-receipt"], description: "Reflect the checked recovery and any remaining owner decision." },
  ],
});

export const premadeScenarios = Object.freeze([
  jobOrderFlightScenario,
  createAndAssignScenario,
  producerUpdateScenario,
  feedbackAuditScenario,
  releaseRecoveryScenario,
]);

export const scenarios = premadeScenarios;

export function getPlane(planeId) {
  return governancePlanes.find((plane) => plane.id === planeId);
}
